"""Init

Revision ID: 50298b85b617
Revises: e5c49752cacc
Create Date: 2023-03-15 16:12:00.835588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50298b85b617'
down_revision = 'e5c49752cacc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
